# Google Cloud Scheduler configuration for expired report deletion job
# T143, T145: Weekly job to hard-delete expired reports
#
# This job runs weekly on Sunday at midnight UTC to permanently delete
# reports that have been expired for more than 90 days (GDPR compliance).
#
# Setup:
# 1. Set CRON_SECRET environment variable in Cloud Run
# 2. Deploy this config: gcloud scheduler jobs create http delete-expired-reports --config=cloud-scheduler-delete.yaml
# 3. Monitor job execution in Cloud Scheduler console

name: delete-expired-reports
description: Weekly job to permanently delete expired reports (hard delete)
schedule: "0 0 * * 0"  # Weekly on Sunday at midnight UTC
time_zone: UTC
attempt_deadline: 600s  # 10 minutes (deletion may take longer)

http_target:
  uri: https://YOUR_BACKEND_URL/api/cron/delete-expired-reports
  http_method: POST

  headers:
    Content-Type: application/json
    X-Cron-Secret: ${CRON_SECRET}

  # Optional: Add authentication if using Cloud Run
  # oidc_token:
  #   service_account_email: YOUR_SERVICE_ACCOUNT@YOUR_PROJECT.iam.gserviceaccount.com

retry_config:
  retry_count: 3
  max_retry_duration: 1800s  # 30 minutes
  min_backoff_duration: 10s
  max_backoff_duration: 120s
  max_doublings: 5

# Job execution settings
# - Job runs weekly on Sunday at midnight UTC
# - Retries up to 3 times on failure
# - Each attempt has 10 minute deadline
# - Total retry window is 30 minutes (deletion can be heavy)
#
# GDPR Compliance:
# - Reports created at day 0
# - Soft deleted (expired) at day 30
# - Hard deleted at day 120 (90 days after expiry)
